name: benchmark

on:
  workflow_dispatch:
    inputs:
      warmup:
        description: Number of warmup runs
        default: 5
      runs:
        description: Number of runs
        default: 40

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/latest/download/install
          extra_nix_config: experimental-features = flakes nix-command

      - name: Run benchmarks
        run: |
          nix run . "${{ github.event.inputs.warmup }}" "${{ github.event.inputs.runs }}"

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: |
            results.json
            results.md
